---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.11.2-ce.0
    hostname: gitlab.local
    container_name: gitlab
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      GITLAB_ROOT_EMAIL: "admin@gitlab.local"
      GITLAB_ROOT_PASSWORD: "Abcd1234!"
      GITLAB_OMNIBUS_CONFIG: |
        puma['worker_processes'] = 0 # disable cluster mode to avoid more memory usage
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  gitlab_runner:
    image: gitlab/gitlab-runner:v17.11.1
    container_name: gitlab-runner
    depends_on:
      - gitlab
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
    entrypoint: >
      gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner

  # nexus:
  #   image: sonatype/nexus3:3.79.1-java17-alpine
  #   container_name: nexus
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - nexus_data:/nexus-data

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
  nexus_data:
