image: maven-cpp:latest

stages:
  - build
  - upload
  - deploy_to_test
  - deploy_to_acceptance

variables:
  MAVEN_CLI_OPTS: "-B -e -V --settings ./maven-settings.xml"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

upload:
  stage: upload
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - main
  dependencies:
    - build

deploy_to_test:
  stage: deploy_to_test
  environment:
    name: test
  script:
    - python3 deploy-to.py test
  only:
    - main
  dependencies:
    - build

deploy_to_acceptance:
  stage: deploy_to_acceptance
  environment:
    name: acceptance
  script:
    - python3 deploy-to.py acceptance
  only:
    - main
  when: manual
  needs:
    - deploy_to_test
  allow_failure: false
