image: maven-cpp:latest

stages:
  - extract
  - build
  - upload
  - deploy_to_test
  - release
  - deploy_to_acceptance

variables:
  MAVEN_CLI_OPTS: "-B -e -V --settings ./maven-settings.xml"

extract_version:
  stage: extract
  script:
    - echo "VERSION=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)" > version.env
  artifacts:
    reports:
      dotenv: version.env

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

upload:
  stage: upload
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - main
  dependencies:
    - build

deploy_to_test:
  stage: deploy_to_test
  environment:
    name: test
  script:
    - python3 deploy-to.py test
  only:
    - main
  dependencies:
    - build

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - main
  needs:
    - job: extract_version
  release:
    tag_name: "$VERSION"
    name: 'Fibonacci release $VERSION'
    description: 'Release of Fibonacci command line application'

deploy_to_acceptance:
  stage: deploy_to_acceptance
  environment:
    name: acceptance
  script:
    - python3 deploy-to.py acceptance
  only:
    - main
  when: manual
  needs:
    - deploy_to_test
  allow_failure: false
