image: maven-cpp:latest

stages:
  - build
  - upload_to_nexus
  - deploy_to_test
  - deploy_to_acceptance

variables:
  MAVEN_CLI_OPTS: "-B -e -V --settings ./maven-settings.xml"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

upload_to_nexus:
  stage: upload_to_nexus
  only:
    - main
  script:
    - mvn $MAVEN_CLI_OPTS deploy

deploy_to_test:
  stage: deploy_to_test
  environment:
    name: test
  only:
    - main
  script:
    - mvn --batch-mode help:evaluate -Dexpression=project.version -q -DforceStdout
    - python3 deploy-to.py test

deploy_to_acceptance:
  stage: deploy_to_acceptance
  environment:
    name: acceptance
  only:
    - main
  when: manual
  script:
    - python3 deploy-to.py acceptance
