image: maven-cpp:latest

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B -e -V"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: fibonacci/target/test-results.xml

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - main
